apiVersion: v1
kind: Service
metadata:
  name: tsp-mongoexpress-service
  namespace: database
spec:
  type: NodePort
  selector:
    app: mongoexpress
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081  
      nodePort: 32000