apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: database
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb