apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress-0
  namespace: database
  labels:
    app: mongoexpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongoexpress
  template:
    metadata:
      labels:
        app: mongoexpress
    spec:
      containers:
      - name: tsp-mongoexpress-container
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
            value: "false"      
          - name: ME_CONFIG_MONGODB_AUTH_DATABASE
            valueFrom:
              configMapKeyRef:
                name: tsp-mongodb-configmap
                key: auth_db
          - name: ME_CONFIG_MONGODB_AUTH_USERNAME
            valueFrom:
              secretKeyRef:
                name: tsp-mongodb-secret
                key: mongodb-username
          - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tsp-mongodb-secret
                key: mongodb-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: tsp-mongodb-configmap
                key: db_url