apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tsp-mongodb-servicemonitor
  namespace: monitoring
  labels:
    team: virtualization-final-project
spec:
  endpoints:
  - port: http-metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - database
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb