apiVersion: v1
kind: Service
metadata:
  name: tsp-mongodb-service
  namespace: database
spec:
  selector:
    app: mongodb
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017    